FROM quay.io/keycloak/keycloak:26.3 AS builder

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.3

COPY --from=builder /opt/keycloak/ /opt/keycloak/
USER 0
COPY infra/scripts/keycloak-prod-apply.sh /opt/keycloak/keycloak-prod-apply.sh
RUN chmod +x /opt/keycloak/keycloak-prod-apply.sh
USER 1000
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
